### ISSUE TITLE
New line at the end of file on save

### ISSUE THREAD

**Issue by m-shulipa** [alex18881/JsonL18nResourcesEditor#2]
Sublime Text has an option
```
"ensure_newline_at_eof_on_save": true,
```

which add new line at the end of file and causes problems with l18n (tricky name, btw, saw the #1)

So, when this option is true, it adds a new line to file and keys is not synced with translations messages anymore.

**Comment by alex18881** [comment]
Nikita. Thank you for posting this issue. It would be great if you checked out fixes and posted the small feedback.

**Comment by m-shulipa** [comment]
Not sure if it was fixed. What I'm seeing now: it does not respect `ensure_newline_at_eof_on_save` option, so if you have this option set with `true`, you will see unexpected behavior like this: file was saved without a new line at the end (`git diff` will have message ` No newline at end of file` at the end of file).
As far as I can get you just set this to `false` always while saving file, am I correct?

I'm just curious, is there any way to respect the user settings and do not get translations out of sync (I mean do not swap the lines with translation messages)?
Maybe, just need to:
* when adding a new key to the file with keys - add the empty double brackets to all translations files so we can be sure that line order is the same
* save all translation files when saving one of the files with keys/translations

I don't know if this information is enough.

Sorry, my knowledge in Python not so good to help you...
If you will have any questions or thoughts - please let me know!
