### ISSUE TITLE
All file content gets modified

### ISSUE THREAD

**Issue by m-shulipa** [alex18881/JsonL18nResourcesEditor#3]
Entire file content is marked as modified when I just add a new key with i18n messages OR editing one particular message - `git diff` shows me that I've removed all content and then paste it again.

**Comment by alex18881** [comment]
Nikita. Thank you for posting this issue. It would be great if you checked out fixes and posted here a small feedback.

**Comment by m-shulipa** [comment]
Not fixed in my case - still seeing the changes in the whole file (`git diff` saying that content was deleted then added) in both cases - adding a new key with translations or modify existing translation.
Just found the reason - the settings in project was different: 2 spaces instead of 4 😉

**Comment by alex18881** [comment]
Oh. I see. Thanks for reply. I'll try to use global settings for json formatter.

**Comment by alex18881** [comment]
Nikita, can you please check the fix once again?

**Comment by m-shulipa** [comment]
It works awesome! 🎉 👍🏻 💪🏻
