### ISSUE TITLE
Improve "tab" key behavior

### ISSUE THREAD

**Issue by m-shulipa** [alex18881/JsonL18nResourcesEditor#4]
When I'm adding a new key at the end of file, it puts empty quotes into i18n files.

Imagine the scenario:
when I've finished writing translation key, 
and pressing TAB key, 
if the quotes are empty - put the cursor INTO the quotes.

What do you think?

**Comment by alex18881** [comment]
Nikita. Thank you for posting this issue. It would be great if you checked out fixes and posted the small feedback.

**Comment by m-shulipa** [comment]
👍🏻 It works!
